### ISSUE TITLE
deprecated config/code

### ISSUE THREAD

**Issue by alister** [K-Phoen/KPhoenContactBundle#26]
The "_method" requirement of route "contact_send" in file ".../kphoen/contact-bundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead

 KPhoen\ContactBundle\Form\Type\MessageType: The FormTypeInterface::getName() method is deprecated since version 2.8 and will be removed in 3.0. Remove it from your classes. Use getBlockPrefix() if you want to customize the template block prefix. This method will be added to the FormTypeInterface with Symfony 3.0

**Comment by zapashcanon** [comment]
Hi,

Thanks for the report, #27 should fix it.
