### ISSUE TITLE
FrameworkExtraBundle limited to v3.0

### ISSUE THREAD

**Issue by alister** [K-Phoen/KPhoenContactBundle#32]
The only use appears to be a `@Template` annotation on one controller action. Allowing "^3.0|^4.0|^5.0" should be safe, and longer-term, using the `render()` results directly as a return would allow the removal of the FrameworkExtraBundle entirely.

**Comment by zapashcanon** [comment]
Hi, I didn't use this bundle and Symphony for a long time, so I'm not even sure what you're talking about ; I'll get back to it but I don't know when...

So, you'll have to wait or you can open a PR and I'll of course accept it. :)
