### ISSUE TITLE
Unrecognized options "sender, receiver" under "k_phoen_contact"

### ISSUE THREAD

**Issue by AmiraBedhiafi** [K-Phoen/KPhoenContactBundle#35]
When I run the project I got this error :

> Unrecognized options "sender, receiver" under "k_phoen_contact" 

knowing that I can't understrand if I need to create the redirect_url or not as mentioned below in config file:
`k_phoen_contact:
    redirect_url:       homepage  # the url to redirect the user to once the
                                  # mail is sent
    sender:             { address: 'no-reply@foo.org' }
    receiver:           { address: 'contact@foo.org' }`

**Comment by alister** [comment]
I'm not sure what is going on there, if you are adding the lines as the [example](https://github.com/K-Phoen/KPhoenContactBundle#configyml). I'd suggest using the latest dev-master version (if you aren't already) and seeing if that improves anything.

**Comment by AmiraBedhiafi** [comment]
I am already using the latest dev-master version.Theproblem ,as I mentioned ,is related to the configuration of the bundle.The options "sender" and "receiver" are not recognized.

**Comment by redianthus** [comment]
Hi,

Can you show us your exact configuration file ? With correct indentation etc.

**Comment by AmiraBedhiafi** [comment]
`k_phoen_contact:
    redirect_url:       homepage  # the url to redirect the user to once the
                                  # mail is sent
    sender:             { address: 'me@gmail.com' }
    receiver:           { address: 'test@gmail.com' }`

I added the bundle configuration as mentioned in the config section.
