### ISSUE TITLE
PHP coding conventions missing.

### ISSUE THREAD

**Issue by zapashcanon** [K-Phoen/KPhoenContactBundle#9]
When they are defined, they'll go in CONTRIBUTING.md.

**Comment by zapashcanon** [comment]
@K-Phoen I would like to use [Style CI](https://styleci.io/) to check php coding conventions for us, it proposes automatic PR to correct errors, but, I can't add the repo as I'm not the owner, could you do this ?

They have a nice Symfony template.

**Comment by K-Phoen** [comment]
Done: https://styleci.io/repos/7018780

**Comment by zapashcanon** [comment]
Thanks ! :)

Just a little thing, could you set the Automation level to "Automatically send fixes as pull requests only " ?

**Comment by K-Phoen** [comment]
And also done :)

**Comment by zapashcanon** [comment]
Great ! :)

**Comment by zapashcanon** [comment]
Sorry, a little thing more again... As I don't want to send a useless PR, could you make it send a fix PR ?

**Comment by K-Phoen** [comment]
A fix PR?

Aren't #14 and #15 what you call fix PR?

**Comment by zapashcanon** [comment]
Yep sorry, cf. my EDIT.
